### ISSUE TITLE
I need help in using funModeling 

### ISSUE THREAD

**Issue by beatrizmarcelo** [pablo14/funModeling#19] opened 2022-05-28 19:50 UTC
hi, I am Beatriz and I am a student currently learning how to work with funModeling with the data base of heart_disease on R studio. 
I have been practising and doing some exercises because I think I have understood the theory behind it. However, there are some exercises where I have some doubts, therefore I was hoping someone could help me with them because I understand they will be important for my future and I do not know who to ask for help because my professors could not help me with it... I hope to hear an answer please... I really do not know who I should ask for help. I will leave here the exercises that I am not being able to solve, hoping someone can reach out to me... Thank you 

<img width="685" alt="Screenshot 2022-05-28 at 20 27 44" src="https://user-images.githubusercontent.com/106450075/170840817-f40be844-5f40-4da4-95c6-83da4b3c0e59.png">
<img width="681" alt="Screenshot 2022-05-28 at 20 27 18" src="https://user-images.githubusercontent.com/106450075/170840824-86180f12-f36f-4a68-9716-2f2cfbc8b184.png">
<img width="681" alt="Screenshot 2022-05-28 at 20 28 01" src="https://user-images.githubusercontent.com/106450075/170840831-5b097fd2-ac53-45b7-a2cd-7bc27667e722.png">

**Comment by pablo14** [comment] 2023-04-05 15:28
Hi! This is not a bug, so I'm closing this issue.

**Closed as completed by pablo14** 2023-04-05 15:28 UTC
